name: Build and Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint-and-unit-test:
    name: Lint and Unit Test
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6

      - name: Set up Go
        uses: actions/setup-go@4dc6199c7b1a012772edbd06daecab0f50c9053c # v6
        with:
          go-version: "1.25.5"
      - run: go install go.uber.org/mock/mockgen@latest

      - name: Download dependencies
        run: go mod download

      - name: Generate mocks
        run: go generate ./...

      - name: Verify mocks are up-to-date
        run: |
          git diff --exit-code || (echo "Generated mocks are not up-to-date. Please run 'go generate ./...' locally and push the updated files." && exit 1)

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@1e7e51e771db61008b38414a730f564565cf7c20 # v9.2.0
        # uses: golangci/golangci-lint-action@e7fa5ac41e1cf5b7d48e45e42232ce7ada589601 # v9.1.0
        with:
          version: latest
          args: --timeout=1m

      - name: Run unit tests
        run: go test -v -race ./...

  integration-tests:
    name: Build and Integration Tests
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6

      - name: Set up Go
        uses: actions/setup-go@4dc6199c7b1a012772edbd06daecab0f50c9053c # v6
        with:
          go-version: "1.25.5"

      - name: Download dependencies
        run: go mod download

      - name: Build
        run: go build -v ./...

      - name: Run integration tests
        run: go test -v -tags=integration ./test/integration/...
        env:
          USE_CONTAINER: "false"
          NEO4J_URI: ${{ secrets.AURA_URL }}
          NEO4J_USERNAME: ${{ secrets.AURA_USERNAME }}
          NEO4J_PASSWORD: ${{ secrets.AURA_PASSWORD }}
